# -*- coding: utf-8 -*-
"""train_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gk3AbWwY1hX3SibQCMjh4r6pcVQexVWD
"""
import tensorflow as tf

def make_dataset(data, shuffle=True):
  """
  """
  df = data.copy()

  labels = df['Worldwide']
  features = df.drop(columns = ['Worldwide'])
  ds = tf.data.Dataset.from_tensor_slices((features, labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(ds))

  train_size = int(0.7*len(ds))
  val_size   = int(0.1*len(ds))

  train = ds.take(train_size).batch(20)
  val = ds.skip(train_size).take(val_size).batch(20)
  test = ds.skip(train_size+val_size).batch(20)

  return train,val,test